#!/bin/bash
###############################################################################
# Run ART for all .cfg files that I created
# 	Code generated by Kathleen Hupfeld--Seidler Lab 
#	Last updated Feb. 2018 
###############################################################################

module load matlab 

#Note: for person A, B, & C, the 03 file is for 03_2; for person L, the 01 file is for 01_2
#Note: person C is missing time 01

inputArray="{'subj_A_01.cfg','subj_A_02.cfg','subj_A_03.cfg','subj_A_04.cfg','subj_A_05.cfg','subj_A_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_B_01.cfg','subj_B_02.cfg','subj_B_03.cfg','subj_B_04.cfg','subj_B_05.cfg','subj_B_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_C_01.cfg','subj_C_02.cfg','subj_C_03.cfg','subj_C_04.cfg','subj_C_05.cfg','subj_C_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_D_01.cfg','subj_D_02.cfg','subj_D_03.cfg','subj_D_04.cfg','subj_D_05.cfg','subj_D_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_E_01.cfg','subj_E_02.cfg','subj_E_03.cfg','subj_E_04.cfg','subj_E_05.cfg','subj_E_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

#Person F dropped out: 
#inputArray="{'subj_F_01.cfg','subj_F_02.cfg','subj_F_03.cfg','subj_F_04.cfg','subj_F_05.cfg','subj_F_06.cfg'}"
#matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_G_01.cfg','subj_G_02.cfg','subj_G_03.cfg','subj_G_04.cfg','subj_G_05.cfg','subj_G_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_H_01.cfg','subj_H_02.cfg','subj_H_03.cfg','subj_H_04.cfg','subj_H_05.cfg','subj_H_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_J_01.cfg','subj_J_02.cfg','subj_J_03.cfg','subj_J_04.cfg','subj_J_05.cfg','subj_J_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_K_01.cfg','subj_K_02.cfg','subj_K_03.cfg','subj_K_04.cfg','subj_K_05.cfg','subj_K_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_L_01.cfg','subj_L_02.cfg','subj_L_03.cfg','subj_L_04.cfg','subj_L_05.cfg','subj_L_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"

inputArray="{'subj_M_01.cfg','subj_M_02.cfg','subj_M_03.cfg','subj_M_04.cfg','subj_M_05.cfg','subj_M_06.cfg'}"
matlab -nodesktop -nosplash -r "try; VEMP_Vaper_makeArt($inputArray); catch; end; quit"





